/// <reference types="vitest" />
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath, URL } from 'node:url';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    port: 5173,
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    css: true,
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      // text-summary for the CI log, html to browse locally, lcov so any
      // coverage service or editor plugin can read it later.
      reporter: ['text-summary', 'html', 'lcov'],
      reportsDirectory: './coverage',
      // Report on every source file, not only the ones a test happens to
      // import — otherwise untested files are invisible and the percentage
      // flatters us.
      all: true,
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.{test,spec}.{ts,tsx}',
        'src/test/**',
        'src/**/*.d.ts',
        // Generated by orval from DigiShield_openapi.yaml — regenerated on
        // every `npm run gen:api`, so testing it measures the generator.
        'src/api/generated/**',
        'src/main.tsx',
        'src/vite-env.d.ts',
      ],
      // No thresholds yet — this change measures, it does not gate. Adding a
      // floor is a separate decision, once the number is known.
    },
  },
});
