package com.digishield.ai.domain;

/**
 * A content draft generated by the AI.
 *
 * @param subject the subject / topic
 * @param body    the body content
 * @param verdict the moderation verdict (e.g. SAFE, NEEDS_REVIEW, BLOCKED)
 */
public record TemplateDraft(String subject, String body, String verdict) {
}
